"""empty message

Revision ID: 2aa3e47f2eec
Revises: 2fdd5b7e1d7c
Create Date: 2020-10-24 14:40:04.116322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2aa3e47f2eec'
down_revision = '2fdd5b7e1d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('id_answer_selected', sa.Integer(), nullable=True))
    op.drop_constraint('question_ibfk_2', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'answer', ['id_answer_selected'], ['id'])
    op.drop_column('question', 'is_answer_selected')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('question', sa.Column('is_answer_selected', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_ibfk_2', 'question', 'answer', ['is_answer_selected'], ['id'])
    op.drop_column('question', 'id_answer_selected')
    # ### end Alembic commands ###
