"""empty message

Revision ID: 3f2b62dedb4e
Revises: 4eb13e3a07c7
Create Date: 2020-11-23 20:36:05.227120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f2b62dedb4e'
down_revision = '4eb13e3a07c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('foo', sa.String(length=1), nullable=False))
    op.alter_column('answer', 'description',
               existing_type=mysql.VARCHAR(length=5000),
               nullable=False)
    op.add_column('answer_images', sa.Column('foo', sa.String(length=1), nullable=False))
    op.alter_column('answer_images', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('question', sa.Column('foo', sa.String(length=1), nullable=False))
    op.alter_column('question', 'description',
               existing_type=mysql.VARCHAR(length=5000),
               nullable=False)
    op.add_column('question_images', sa.Column('foo', sa.String(length=1), nullable=False))
    op.alter_column('question_images', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('role', sa.Column('foo', sa.String(length=1), nullable=False))
    op.add_column('user', sa.Column('foo', sa.String(length=1), nullable=False))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user', 'foo')
    op.drop_column('role', 'foo')
    op.alter_column('question_images', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('question_images', 'foo')
    op.alter_column('question', 'description',
               existing_type=mysql.VARCHAR(length=5000),
               nullable=True)
    op.drop_column('question', 'foo')
    op.alter_column('answer_images', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('answer_images', 'foo')
    op.alter_column('answer', 'description',
               existing_type=mysql.VARCHAR(length=5000),
               nullable=True)
    op.drop_column('answer', 'foo')
    # ### end Alembic commands ###
