"""empty message

Revision ID: 4eb13e3a07c7
Revises: 90137410fdf1
Create Date: 2020-10-27 19:11:41.965660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4eb13e3a07c7'
down_revision = '90137410fdf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_answer', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_answer'], ['answer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_question', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_question'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('answer__images')
    op.drop_table('question__images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question__images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_question', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('size', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=False),
    sa.Column('last_update', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_question'], ['question.id'], name='question__images_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('answer__images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_answer', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('size', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=False),
    sa.Column('last_update', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_answer'], ['answer.id'], name='answer__images_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('question_images')
    op.drop_table('answer_images')
    # ### end Alembic commands ###
