"""empty message

Revision ID: 75befeb224d2
Revises: 7ea7941654e9
Create Date: 2020-10-22 18:08:02.068591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75befeb224d2'
down_revision = '7ea7941654e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('alerts_activated', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('id_role', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=80), nullable=False))
    op.create_foreign_key(None, 'user', 'role', ['id_role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'name')
    op.drop_column('user', 'last_update')
    op.drop_column('user', 'id_role')
    op.drop_column('user', 'created')
    op.drop_column('user', 'alerts_activated')
    op.drop_table('role')
    # ### end Alembic commands ###
