"""empty message

Revision ID: 90137410fdf1
Revises: 2aa3e47f2eec
Create Date: 2020-10-24 15:21:09.805565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90137410fdf1'
down_revision = '2aa3e47f2eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
