"""empty message

Revision ID: fe4fee12ded4
Revises: 3f2b62dedb4e
Create Date: 2020-11-23 20:54:02.431983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe4fee12ded4'
down_revision = '3f2b62dedb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'foo')
    op.drop_column('answer_images', 'foo')
    op.drop_column('question', 'foo')
    op.drop_column('question_images', 'foo')
    op.drop_column('role', 'foo')
    op.drop_column('user', 'foo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('foo', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('role', sa.Column('foo', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('question_images', sa.Column('foo', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('question', sa.Column('foo', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('answer_images', sa.Column('foo', mysql.VARCHAR(length=1), nullable=False))
    op.add_column('answer', sa.Column('foo', mysql.VARCHAR(length=1), nullable=False))
    # ### end Alembic commands ###
